### PR TITLE
Noarch

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
why not just merge?

**Comment by carlodri** [comment]
not sure how this goes along with #66? Moreover, comment in `meta.yaml` says "no longer noarch" while adding `noarch: python`: is there something I'm missing?

**Comment by hmaarrfk** [comment]
Both should be addressed now. thank you for your patience.

**Comment by dgasmith** [comment]
> why not just merge?

The CI was not yet complete.

**Comment by hmaarrfk** [comment]
Sorry for the noise on this feedstock.

**Comment by dgasmith** [comment]
We're in good shape now, thank you for your maintenance on these repos! 🙏

**Pull request merged**
