### PR TITLE
add py.typed to 0.24.0

### LINKED ISSUE #81: add `py.typed` to 0.24.0?
### Comment:

Thanks for maintaining this!

`fastapi` pins with `==` to `0.24.0`, but that [`sdist`](https://pypi.org/project/starlette/0.20.4/#files) doesn't include `py.typed` which bothers tools that follow the PEP561 strictly (e.g. `mypy`).

Would it be possible to get a historical build of that version with this before `pip install`:

```yaml
outputs:
  - name: {{ name }}
    build:
      script: 
        - python -c "__import__('pathlib').Path('starlette/py.typed').touch()"
        - python -m pip install . --no-deps --no-build-isolation -vv
```

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Notes:
- fixes #81

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/starlette ready for review

**Comment by bollwyvl** [comment]
@conda-forge/starlette ping

**Comment by thewchan** [comment]
@bollwyvl Thanks!

**Pull request merged**
