### PR TITLE
Python migrations

### PR DESCRIPTION
**Pull request by hmaarrfk**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dgasmith** [comment]
It isn't clear to me that #65 was a good change as starlette itself is still pure-python and does not require compilation.

**Comment by hmaarrfk** [comment]
How else would you build for less than 3.10?

**Comment by hmaarrfk** [comment]
Should you depend on typing extensions for all versions? including python 3.10?

**Comment by hmaarrfk** [comment]
Ok. I can make the PR to have typing extensions for all versions.

Usually I'm scared that things get pulled into the main python distribution, but it seems like typing extensions is installable on python 3.10

**Pull request closed without merging**
